services:
  # 1. Base de Datos
  db:
    image: postgres:15
    container_name: docapp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: usu2020
      POSTGRES_DB: docapp_db
    #ports:
    # - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend API
  backend:
    build: ./backend
    container_name: docapp-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Estas variables deben coincidir con database.js
      DB_USER: postgres
      DB_PASSWORD: usu2020
      DB_DATABASE: docapp_db
      DB_HOST: db
      DB_PORT: 5432
      PORT: 5000
      JWT_SECRET: supersecretkey
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  # 3. Frontend React
  frontend:
    build: ./frontend
    container_name: docapp-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # React necesita saber dónde está el backend
      - REACT_APP_API_URL=http://localhost:5000
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data:
